### ISSUE TITLE
Question : How to deploy Alfresco in HTTPS with Helm

### ISSUE THREAD

**Issue by TOTOleHero** [Alfresco/acs-community-deployment#129]
Hello, 

How can i deploy Alfresco in full SSL/HTTPS with Helm (pod, service and ingress) ?

And for ingress how to setup letencrypt

I need to add this annotations in ingress, but no option is available for this

```
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      ingress.kubernetes.io/ssl-redirect: "true"
```
And to manage HTTP on ingress we need to add 

```
  spec:
    rules:
       ...
    tls:
    - hosts:
      - my-https-host.com
      secretName: my-https-host-tls  
```

But no option exist in Helm chart

Thanks
